### ISSUE TITLE
cannot insert a range that the start equal with the end

### ISSUE THREAD

**Issue by dwgeneral** [jeffparsons/rangemap#10]
in src/map.rs
```rust
/// Panics if range `start >= end`.
    pub fn insert(&mut self, range: Range<K>, value: V) {
        // We don't want to have to make empty ranges make sense;
        // they don't represent anything meaningful in this structure.
        assert!(range.start < range.end);
```

I think we should allow the range params that the start equal with the end, it's meaningful in real business scence, 
would you mind I change the code for this?

**Comment by jeffparsons** [comment]
Hi @dwgeneral, thanks for getting in touch! :wave: 

I'm not fundamentally opposed to this change, but it would complicate some other things so I'd want to carefully understand the implications first.

E.g. what would it mean to add a zero-length range at the start of an existing range? Does the existing range's start get moved to the next possible value? I don't think all types you might want to put in the `RangeMap` even necessarily support that.

Maybe if you tell me more about your use case it would help me understand the best way to approach this.

**Comment by jeffparsons** [comment]
@dwgeneral I have a work-in-progress PR that introduces a type for what I think matches your use case: https://github.com/jeffparsons/rangemap/pull/15.

It works, but I have a few things I want to clean up before landing it, as you can see in the "TODO" section on that PR.

**Comment by jeffparsons** [comment]
@dwgeneral I've just released a new version that supports inclusive ranges: https://docs.rs/rangemap/0.1.6/rangemap/

I know this isn't quite what you were asking for, but do you think it might work for your use case?

I'm still considering allowing zero-length ranges in `RangeMap`, but it'll be a bit tricky to define an API that supports that but isn't horrible to use. E.g. I don't want to require that your key type supports successor/predecessor functions in the general case, because it's probably extra fiddling around that's not needed for most people, but that would be _necessary_ when inserting zero-length ranges. Maybe just having a separate `insert_possibly_zero_length` function with the extra trait bounds (TODO: good name :sweat_smile:) would be enough.

Does that make some kind of sense?

**Comment by jeffparsons** [comment]
By the way, I'd love to hear about details of your use case if you're able to share. :smiley:

**Comment by Kinrany** [comment]
Would it make sense to just ignore empty ranges instead of panicking? This seems equivalent to adding 0 to a number.

**Comment by Kinrany** [comment]
https://github.com/jeffparsons/rangemap/pull/112
