### ISSUE TITLE
Can we reduce dev-dependencies?

### ISSUE THREAD

**Issue by avl** [jeffparsons/rangemap#12]
The dependency on skeptic is pulling in a huge number of dependencies.

It would be very nice if this could be configured away somehow.

I know it doesn't affect the binary, but in a security-conscious organisation anything admitted onto build-servers needs to pass a security review, and the "skeptic"-dependency pulls in tens of crates to verify.

**Comment by jeffparsons** [comment]
Hi @avl, thanks for getting in touch! :wave: 

Ah, yes. I think this is because skeptic needs to be in `[build-dependencies]` to get run as part of the doc generation.

I _think_ I can solve this by making it only included if you enable an optional-but-default feature, and then if you turn that feature off all that would break is doc generation.

**Comment by jeffparsons** [comment]
@avl How about this: https://github.com/jeffparsons/rangemap/pull/13

**Comment by rsf-team** [comment]
> @avl How about this: #13

Looks great!

**Comment by jeffparsons** [comment]
Published https://crates.io/crates/rangemap/0.1.5
