### ISSUE TITLE
Cannot insert a range that includes the maximum value of a given key type

### ISSUE THREAD

**Issue by rzumer** [jeffparsons/rangemap#9]
I want to use `rangemap` using u16 indices, where the multiple entries in the map are expected to fill the full 0-65535 range, but since `insert()` only accepts an exclusive range, and 65536 is out of range for my index type (`K`), it is impossible to create an entry that spans the full range. I am forced to use a different type, which is error-prone, or be off by one.

Easiest solution would be to change all uses of `Range` with `RangeInclusive` and bump the minor version.

**Comment by jeffparsons** [comment]
@rzumer  Hey, sorry this has taken so long for me to notice. I somehow had "watch" disabled for my own repo...  :sweat_smile: 

I'd like to support your use case, but I don't think I want to just change to inclusive ranges for everything. In _my_ use cases, for example, it's much more convenient to have the upper end be _exclusive_, because otherwise I'll be subtracting the smallest possible value from my upper bounds all the time.

How about a new pair of `RangeInclusiveMap` / `RangeInclusiveSet` types? I think that would be the cleanest way to make the distinction. (I think Rust made the right call here; Ruby tries to squish all different kinds of ranges together in one `Range` class, and the result is that it's full of bugs. :scream_cat:)

**Comment by rzumer** [comment]
Your solution seems reasonable to me, thanks for the response.

**Comment by jeffparsons** [comment]
I have a work-in-progress `RangeInclusiveMap` here: https://github.com/jeffparsons/rangemap/pull/15.

It works, but I have a few things I want to clean up before landing this, as you can see in the "TODO" section on that PR.

**Comment by jeffparsons** [comment]
@rzumer I've just released a new version that supports inclusive ranges: https://docs.rs/rangemap/0.1.6/rangemap/

If you do end up using this, please let me know if you run into any trouble. The API for providing successor/predecessor functions might be a little confusing, but I think it's necessary for it to exist at least in some form. I'm open to suggestions on how to make it neater / more obvious.

And I'd love to hear details of your use case if you're able to share! :smiley:

**Comment by rzumer** [comment]
Thanks a lot! I'll see if I can write a self-contained module that uses it and post it in a comment here once it is in a usable state.

**Comment by rzumer** [comment]
[Here](https://gist.github.com/rzumer/c3442f55c98a4e3faf3b37e81c7ba672) is my first shot at implementing a memory controller using `RangeInclusiveMap`. Its only dependencies should be `num_traits` and `rangemap`. Sorry it took me a while to get back to it.

It is part of a CPU emulator I've been working on slowly. Since many computer systems have multiple memory chips that share the same virtual memory space, a memory controller like this translates redirects read and write requests to the right memory chips. The overlapping chips and banked memory tests are some simplified examples of how different chips might map to virtual memory.

Overall I think `RangeInclusiveMap` simplified the implementation substantially, thanks again for adding that.

**Comment by jeffparsons** [comment]
Hey, @rzumer, that looks really cool. Thanks for sharing! :sunglasses: 

Is this part of a broader project, or is it a CPU emulator for its own sake?

By the way, I recently pushed some new code introducing a `gaps` iterator that lets you iterate over all the non-covered areas around stored ranges inside a specified outer range. Not sure if relevant to what you're doing -- if it is, I can publish a new release.
